### ISSUE TITLE
Distorted UI on Mac

### ISSUE THREAD

**Issue by alexandershalin** [pyarchinit/heroquest_legends#9]
Unfortunately, I can't try the app under Windows yet to compare, but it seems that UI is distorted under on Mac.
See screenshot attached.[
![Снимок экрана 2021-04-20 в 18 00 26](https://user-images.githubusercontent.com/5166305/115419005-a3ff8b80-a202-11eb-9563-782b35cbb06c.png)
](url)

**Comment by alexandershalin** [comment]
Seems it is caused by Viner Hand IT font. Will check.

**Comment by alexandershalin** [comment]
No, this issue is not related to the font family.

**Comment by pyarchinit** [comment]
Did you understand why?

**Comment by alexandershalin** [comment]
Not yet, unfortunately, will investigate further.

**Comment by alexandershalin** [comment]
<img width="1440" alt="Снимок экрана 2021-04-22 в 17 45 41" src="https://user-images.githubusercontent.com/5166305/115734792-a55fbe00-a392-11eb-9a5c-0ffa9d92ccf1.png">
 
This issue was caused by 

`<string notr="true">background-color: rgb(255, 255, 255);</string>`

in UI file

**Comment by pyarchinit** [comment]
OK! proceed!

**Comment by pyarchinit** [comment]
![immagine](https://user-images.githubusercontent.com/1929829/115777943-372cf280-a3b6-11eb-97bc-b4e953aa4615.png)

**Comment by alexandershalin** [comment]
Confirmed to be fixed.
